const express = require('express')
const cors = require('cors')
const categoryRouter = require('./routers/category')
const authRouter = require('./routers/auth')
const productRouter = require('./routers/product')
const orderRouter=require('./routers/order')
const app = express()
app.use(express.json())
app.use(cors())
app.use('/api', categoryRouter)
app.use('/api', authRouter)
app.use('/api',productRouter)
app.use('/api',orderRouter)
module.exports = app